[project]
name = "4210-model-operationalization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
    "ipykernel",
    "matplotlib",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "scikit-learn",
    "seaborn",
]
